CREATE TABLE CUSTOMER
(
	Customer_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Customer_Name VARCHAR(50) NOT NULL,
	Customer_Surname VARCHAR(50) NOT NULL,
	Customer_Phone VARCHAR(10) NOT NULL,
	Customer_Email VARCHAR(100) NOT NULL
);
GO

CREATE TABLE GENRE
(
	Genre_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Genre_Description VARCHAR(50) NOT NULL
);
GO

CREATE TABLE SNACK
(
	Snack_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Snack_Name VARCHAR(50) NOT NULL,
	Snack_Description VARCHAR(50) NOT NULL,
	Snack_Quantity INT NOT NULL,
	Snack_UnitCost MONEY NOT NULL,
	Snack_Price MONEY NOT NULL
);
GO

CREATE TABLE SNACK_SALE
(
	Snack_Sale_ID int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Snack_SaleDate DATE NOT NULL
);
GO

CREATE TABLE MOVIE
(
	Movie_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Movie_Name VARCHAR(50) NOT NULL,
	Genre_ID INT NOT NULL,
	Movie_Duration TIME NOT NULL,
	Age_Restriction VARCHAR(50) NOT NULL,
	Release_Date DATE NOT NULL,
	Withdrawal_Date DATE NOT NULL,
	CONSTRAINT FK_Genre FOREIGN KEY(Genre_ID) REFERENCES GENRE(Genre_ID)
);
GO

CREATE TABLE BOOKING
(
	Booking_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Movie_ID INT NOT NULL,
	Customer_ID INT NOT NULL,
	Total_TicketCost MONEY NOT NULL,
	NumberOfSeats INT NOT NULL,
	Tickets_SaleDate DATE NOT NULL,
	CONSTRAINT FK_Movie FOREIGN KEY(Movie_ID) REFERENCES MOVIE(Movie_ID),
	CONSTRAINT FK_Customer FOREIGN KEY(Customer_ID) REFERENCES CUSTOMER(Customer_ID)
);
GO

CREATE TABLE SNACK_TRANSACTION
(
	Snack_Sale_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Snack_ID INT NOT NULL,
	Quantity_Ordered INT NOT NULL,
	Unit_Price MONEY NOT NULL,
	CONSTRAINT FK_SnackTransaction 
	FOREIGN KEY (Snack_Sale_ID) REFERENCES SNACK_SALE(Snack_Sale_ID),
	CONSTRAINT FK_Snack
	FOREIGN KEY (Snack_ID) REFERENCES SNACK(Snack_ID)
);
GO